"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import Image from "next/image";

/**
 * IraqMap - Realistic AI-generated Iraq map with branch location pins
 * 
 * Shows real Iraq map generated by AI with pins at branch cities:
 * - Baghdad (بغداد) - HQ
 * - Babel (بابل)
 * - Karbala (كربلاء)
 * - Najaf (النجف)
 * - Dhi Qar (ذي قار)
 * - Maysan (ميسان)
 * 
 * Pin positions calibrated to match the AI-generated map image
 */

interface BranchPin {
  id: string;
  name: string;
  nameEn: string;
  x: number;  // percentage position on map image
  y: number;
  isHQ: boolean;
}

// Positions calibrated to match the realistic AI-generated Iraq map image
const branchPins: BranchPin[] = [
  { id: "baghdad", name: "بغداد", nameEn: "Baghdad", x: 52, y: 40, isHQ: true },
  { id: "babel", name: "بابل", nameEn: "Babel", x: 49, y: 47, isHQ: false },
  { id: "karbala", name: "كربلاء", nameEn: "Karbala", x: 42, y: 44, isHQ: false },
  { id: "najaf", name: "النجف", nameEn: "Najaf", x: 38, y: 51, isHQ: false },
  { id: "dhiqar", name: "ذي قار", nameEn: "Dhi Qar", x: 55, y: 58, isHQ: false },
  { id: "maysan", name: "ميسان", nameEn: "Maysan", x: 63, y: 54, isHQ: false },
];

export default function IraqMap() {
  const [activePin, setActivePin] = useState<string | null>(null);

  return (
    <div className="relative w-full max-w-md mx-auto lg:mx-0">
      {/* Glow behind map */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-3/4 h-3/4 bg-brand-green/8 rounded-full blur-3xl" />

      {/* 3D Logo floating above map */}
      <motion.div
        animate={{ y: [0, -10, 0], rotateY: [0, 10, 0, -10, 0] }}
        transition={{ duration: 6, repeat: Infinity, ease: "easeInOut" }}
        className="absolute -top-4 left-1/2 -translate-x-1/2 z-30"
        style={{ perspective: "800px" }}
      >
        <div className="relative w-14 h-14 sm:w-18 sm:h-18" style={{ transformStyle: "preserve-3d" }}>
          <Image
            src="/images/logo.png"
            alt="شعار حبيب الساعدي"
            fill
            className="object-contain drop-shadow-[0_8px_32px_rgba(74,222,64,0.4)]"
          />
        </div>
      </motion.div>

      {/* Realistic Iraq Map Image */}
      <motion.div
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 1, ease: "easeOut" }}
        className="relative w-full"
      >
        <Image
          src="/images/iraq-map.png"
          alt="خريطة العراق - فروع حبيب الساعدي"
          width={896}
          height={1200}
          className="w-full h-auto"
          priority
        />

        {/* Interactive Pin Overlays */}
        {branchPins.map((pin, i) => {
          const isActive = activePin === pin.id;
          return (
            <motion.div
              key={pin.id}
              initial={{ opacity: 0, scale: 0 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 0.8 + i * 0.15, duration: 0.4, type: "spring" }}
              className="absolute z-20 cursor-pointer group"
              style={{
                left: `${pin.x}%`,
                top: `${pin.y}%`,
                transform: "translate(-50%, -50%)",
              }}
              onMouseEnter={() => setActivePin(pin.id)}
              onMouseLeave={() => setActivePin(null)}
            >
              {/* Pulse ring */}
              <div
                className={`absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 rounded-full bg-brand-green/30 ${
                  pin.isHQ ? "w-8 h-8 sm:w-10 sm:h-10" : "w-5 h-5 sm:w-7 sm:h-7"
                }`}
                style={{
                  animation: "pulse 2.5s ease-in-out infinite",
                }}
              />

              {/* Pin dot */}
              <div
                className={`relative rounded-full border-2 border-brand-green shadow-[0_0_12px_rgba(74,222,64,0.5)] transition-all duration-300 ${
                  pin.isHQ
                    ? "w-4 h-4 sm:w-5 sm:h-5 bg-brand-green"
                    : "w-3 h-3 sm:w-3.5 sm:h-3.5 bg-brand-green/30 group-hover:bg-brand-green"
                } ${isActive ? "scale-125" : ""}`}
              >
                {pin.isHQ && (
                  <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-1.5 h-1.5 sm:w-2 sm:h-2 bg-brand-dark rounded-full" />
                )}
              </div>

              {/* Tooltip label on hover */}
              <motion.div
                initial={{ opacity: 0, y: 5 }}
                animate={{ opacity: isActive ? 1 : 0, y: isActive ? 0 : 5 }}
                className="absolute -top-10 left-1/2 -translate-x-1/2 whitespace-nowrap z-30"
              >
                <div className="glass rounded-lg px-3 py-1.5 text-center shadow-lg">
                  <p className="text-xs sm:text-sm font-bold text-brand-green">{pin.name}</p>
                  <p className="text-[8px] sm:text-[9px] text-brand-gray">
                    {pin.isHQ ? "المقر الرئيسي" : "فرع"}
                  </p>
                </div>
              </motion.div>

              {/* HQ badge */}
              {pin.isHQ && (
                <div className="absolute -bottom-5 left-1/2 -translate-x-1/2 whitespace-nowrap">
                  <span className="bg-brand-green text-brand-dark text-[7px] sm:text-[8px] font-black px-2 py-0.5 rounded-full">
                    المقر الرئيسي
                  </span>
                </div>
              )}
            </motion.div>
          );
        })}
      </motion.div>

      {/* Active pin info panel at bottom */}
      {activePin && (
        <motion.div
          initial={{ opacity: 0, y: 5 }}
          animate={{ opacity: 1, y: 0 }}
          className="absolute bottom-2 left-1/2 -translate-x-1/2 glass rounded-xl px-4 py-2.5 text-center z-20"
        >
          <p className="text-sm font-bold text-brand-green">
            {branchPins.find((p) => p.id === activePin)?.name}
          </p>
          <p className="text-[10px] text-brand-gray">
            {branchPins.find((p) => p.id === activePin)?.isHQ ? "الفرع الرئيسي" : "فرع"}
          </p>
        </motion.div>
      )}

      {/* Corner decorations */}
      <div className="absolute top-0 right-0 w-8 h-8 border-t-2 border-r-2 border-brand-green/20 rounded-tr-lg" />
      <div className="absolute bottom-0 left-0 w-8 h-8 border-b-2 border-l-2 border-brand-green/20 rounded-bl-lg" />
    </div>
  );
}
